env:
  matrix:
  - JDK=openjdk8
dist: trusty
sudo: required
services:
- docker
before_script:
- jdk_switcher use $JDK
script:
- "./mvnw clean install package -DskipTests dockerfile:build dockerfile:push -Ddocker.repository=$TRAVIS_REPO_SLUG"
