env:
  matrix:
  - JDK=openjdk8
  global:
  - secure: wrYFeyQEYM6R1PIZ4aSVsRgE2ZzdO+9BfKWe2Ki2qNEcy19M3baysoZj0v/ELIQzkDOP2+ZUZnuvMNFRevj8P8BgDgM2XFcVX3owcJVO5QEt2VdxSfTweg6parSk/W7FD2mYFVNG8SNoZiTzxHglAXAgFn/904YN14HUt00J+Iy4raT/7JqGp0EoASkFM5nxvBISxuGHfrWZNhUe0MFTJGfTq7pa3GIppo/d+tqJHSgLHStgbtYp/UZpEELJQ3Qkxk2zENgeHlOqb/zmSGTTLbi0UU4Qy1PCzLnKjy6WVIte+s6k1d0Kxdz9UVPqDhoZ3UK1w1FkHOLb7JL37wwDOLxtLDjaQRkcazEfNmjOHD/LLQN+jgTPYNszAMNvQRpyN5gpL9Ej5Ez79n82MMezos7+/OLCy18M0Tw1tz6Qtzit27tMt2Y5ZeaGsEHgjCNi2QBOUjbj0+pA4GOWcJWMepnNVa4tiUGOZaNkGlmJ2vWTBPOG73BD45H8JOYjsvqOHz3ArImdkMxgZs/iVrq+qI3b4deTn3FEtSELwNNYIK52REICw6iFFcsarH3vABLNOo9cnIyurWvAKc3xANvo+DdYfdAgqJhzDzqi5yLNBaJutoXSKlKz9qgawIU8t3kqxSYe1GhGibE5Tod0618V+wMcGmsvR+9mFDMw9dFZm78=
  - secure: VHlrP4ydZxF9BzWDcIPUnEU1fQs2TeoQIknkwT0iZBBLNuj1McAaZkZySbGJ5YBpAAU5QGEBLlBTo/sOo3dSvW9Ku19WJ36P1+p9fzaD51kxgd3zPSkdJkCe+cRLksjnujNnc4K2F5KLlAdp/v5nzJaie/tZZz22Paau6KvaJL3m3u+ORFHREDgbA+z1PwixFrMJV1R/xsJuAsqmwAo17thYnIWBLSwY2Vgk/iJsEsDID0B3Xy/e+4r7iOZ9M5YWg8GBg6MJaA52pYWVXOjoiVX7x9uBE+l5EvMfxeAzUAqV0gojkisVdmcL/JYSdZDtUJt2ArYskyKlOiZJQWgfCzk+WZRTcPL4OUcPx2URpi3ROJ5Skhs2LhGAfWeqMswUAhDLRh58JtXLO6Zs8P703TALpH2NYZDna2boP6AnZpbztPVMyJKhB7ygm3bYUJ20qBosHWDrQBgDdNCct2cuK6FQeVFE475QaHXNHX+G8Ov+KJcE12oDJHGP7sq9QEjr2kw1zgctkEcOK50VS9e+Hg5UCsSo/qg7kRUeGg/cyqGTmAaMDjN3vwk6X6chA3u1qPioY/UxfxO5EmdrswH0Du835dJwQKvnswKSKW0FyDiwOwOlhOvweNXpXvjQ0x9eVIpU0kbzpNHp2Pnx8KaGQ9LT6UpRdq8ecpNBAvZvoko=
dist: trusty
sudo: required
services:
- docker
before_script:
- jdk_switcher use $JDK
script:
# - "./mvnw clean install -B"
# - "./mvnw clean package -DskipTests"
- "./mvnw clean package -DskipTests dockerfile:deploy -Ddocker.repository=$TRAVIS_REPO_SLUG"

# after_success:
# - docker login -u $DOCKER_USER -p $DOCKER_PASS
# - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
# - export IMAGE_NAME=$DOCKER_USER/fhir-adaptor
# - docker build -t $IMAGE_NAME:$COMMIT .
# - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
# - docker push $IMAGE_NAME
